
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Leren1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ArticleContent
{

    public string ObjectID { get; set; }

    public string ContentString { get; set; }

    public string ArticleID { get; set; }

    public int Sections { get; set; }



    public virtual ArticleHeader ArticleHeader { get; set; }

}

}
